### ISSUE TITLE
Question: Is Ratel a HAL? My thoughts.

### ISSUE THREAD

**Issue by adokitkat** [PMunch/ratel#11]
Hi! Is this project similar to [embedded-hal](https://github.com/rust-embedded/embedded-hal)?

I am in a search for a way to use Nim on embedded devices which is user-friendly and not a headache. I personally use ESP32s the most and I would really like to use them comfortably with Nim. I tried many ways :

* [Nesper](https://github.com/EmbeddedNim/nesper) - uses ESP-IDF (better than Arduino imho) but is just a wrapper which is 1) not finished, 2) is in a need of constant updating to be in-line with upstream and also 3) only for ESP32s
* some Nim on Arduino projects - it's Arduino...
* compiling Nim code as a library and statically link it with ESP-IDF project - I had weird bugs introduced when passing values between C and Nim code which were not integers (Probably my mistake? Or just some Xtensa weirdness....)

but each has it's own flaws. There are also ways I did not try yet:

* your [Futhark ](https://github.com/PMunch/futhark)with ESP-IDF - could work well (???) but it's ESP32 specific
* Zephyr / [Nephyr](https://github.com/EmbeddedNim/nephyr)
* you tell me (please)

I really like the premise of Ratel but I feel like adding embedded targets manually it's just not plausible and should be somehow automated. 

One way I did not really tried yet and also did not mention above is a usage of SVD files. I found out about this only recently so maybe I am totally wrong but these in combination with a HAL could be the answer. There also is [svd2nim](https://github.com/EmbeddedNim/svd2nim) package similar to Rust's [svd2rust](https://github.com/rust-embedded/svd2rust). This way should be embedded target agnostic.

However all of this requires a great amount of time to be researched and worked on so... And I am not that skilled to pull it off. Those are just my thoughts and speculations.

If I am wrong then please correct me.

**Comment by PMunch** [comment]
Yes, it is similar to embedded-hal in concept. The goal is to make programming against microcontrollers as clean and fast as possible to do in Nim.

Currently Ratel doesn't have ESP32 support, but it's on the list of boards I want to get implemented first. Unfortunately embedded targets differ enough that doing everything automatically wouldn't really be feasible. SVDs might work for ARM Cortex chips, but wouldn't really help for anything else AFAIK. Luckily the process of writing board support is fairly simple, and I want to make it even easier. I'm currently working on wrapping more boards and writing the documentation on how to do this. And as I go I discover small things that could be done to make things easier. Hopefully once the documentation is done it should be fairly easy to get more boards integrated.

**Comment by adokitkat** [comment]
Then I think I'll wait for the documentation. 

Btw ESP's also have SVD files released: https://github.com/espressif/svd

Thank you for answer.
